# Pandas Tips

In [1]:
# how to check version of pandas
import pandas as pd
print(pd.__version__)

3.0.0

In [2]:
# another way to check version of pandas
import pandas as pd
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 366ccdfcd8ed1e5543bfb6d4ee0c9bc519898670
python                : 3.14.3
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 3.0.0
numpy                 : 2.4.2
dateutil              : 2.9.0.post0
pip                   : 26.0.1
Cython                : None
sphinx                : None
IPython               : 9.9.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : 3.10.8
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None

In [ ]:
# 02_make data frame
df = pd.DataFrame({"data": [1,2,3,4], "columns": ["a", "b", "c", "d"]})
df

   data columns
0     1       a
1     2       b
2     3       c
3     4       d

In [8]:
# numpy array to create a data frame
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
df = pd.DataFrame(arr, columns=["a", "b", "c"])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
# numpy array use to create a data frame with index
arr = pd.DataFrame(np.random.rand(5,9))
arr

,0,1,2,3,4,5,6,7,8
0,0.236630,0.500433,0.486802,0.579648,0.961158,0.760708,0.334583,0.584263,0.693540
1,0.097160,0.606327,0.472803,0.321326,0.135374,0.156396,0.873464,0.664410,0.325536
2,0.642674,0.038590,0.532511,0.118497,0.824485,0.788243,0.829362,0.049393,0.403812
3,0.757425,0.564037,0.202546,0.834905,0.009539,0.892196,0.404881,0.391524,0.467031
4,0.268386,0.704549,0.639577,0.582201,0.201466,0.856492,0.886238,0.907845,0.416127

# 03- how to remane columns in pandas

In [11]:
# 03- how to remane columns in pandas
df.rename(columns={"a": "A", "b": "B", "c": "C"}, inplace=True)

In [12]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#rename the columns in pandas
df.columns=['Aa' , 'Bb', 'Cc']
df

   Aa  Bb  Cc
0   1   2   3
1   4   5   6
2   7   8   9

In [16]:
# replace any character in the column name with another character
df.columns = df.columns.str.replace('a', 'A').str.replace('b', 'B').str.replace('c', 'C')
df

   AA  BB  CC
0   1   2   3
1   4   5   6
2   7   8   9

In [20]:
df.replace('a', 'A', regex=True).replace('b', 'B', regex=True).replace('c', 'C', regex=True)

   Aa_Aa_  Bb_Bb_  Cc_Cc_
0       1       2       3
1       4       5       6
2       7       8       9

In [22]:
df

   Aa_Aa_  Bb_Bb_  Cc_Cc_
0       1       2       3
1       4       5       6
2       7       8       9

In [26]:
df.rename(columns ={'Aa_Aa_': 'A', 'Bb_Bb_': 'B', 'Cc_Cc_': 'C'}, inplace=True)

In [27]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
#add prefix to column names in pandas
df = df.add_prefix('A')

In [29]:
df

   AA  AB  AC
0   1   2   3
1   4   5   6
2   7   8   9

# 04- using template data

In [30]:
import pandas as pd
import numpy as np
import seaborn as sns

kashti = sns.load_dataset('titanic')
kashti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [31]:
# summary of the data frame
kashti.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [32]:
# columuns names
kashti.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

# 05_ using your own data

In [33]:
df = pd.read_csv('E:\Machine Learning\pandas\population.csv')

<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\mk\AppData\Local\Temp\ipykernel_29004\2177268622.py:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  df = pd.read_csv('E:\Machine Learning\pandas\population.csv')

In [34]:
df.head(3)

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06

# 06_ Reverse row order

In [39]:
import seaborn as sns
import pandas as pd

phool = sns.load_dataset('tips')
df = phool.head()
df

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [38]:
df.loc[:: -1].head()

   total_bill   tip     sex smoker  day    time  size
4       24.59  3.61  Female     No  Sun  Dinner     4
3       23.68  3.31    Male     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3
1       10.34  1.66    Male     No  Sun  Dinner     3
0       16.99  1.01  Female     No  Sun  Dinner     2

In [40]:
df.loc[:: -1].reset_index(drop=True).head( )

   total_bill   tip     sex smoker  day    time  size
0       24.59  3.61  Female     No  Sun  Dinner     4
1       23.68  3.31    Male     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3
3       10.34  1.66    Male     No  Sun  Dinner     3
4       16.99  1.01  Female     No  Sun  Dinner     2

# 07_reverse columns order

In [41]:
df.loc [:, :: -1].head()

   size    time  day smoker     sex   tip  total_bill
0     2  Dinner  Sun     No  Female  1.01       16.99
1     3  Dinner  Sun     No    Male  1.66       10.34
2     3  Dinner  Sun     No    Male  3.50       21.01
3     2  Dinner  Sun     No    Male  3.31       23.68
4     4  Dinner  Sun     No  Female  3.61       24.59

In [47]:
# df.loc [:, :: -1].reset_index(drop=True).head()
# reverse the columns order and reset the index
df.loc [:, :: -1].reset_index(drop=True).head()

   size    time  day smoker     sex   tip  total_bill
0     2  Dinner  Sun     No  Female  1.01       16.99
1     3  Dinner  Sun     No    Male  1.66       10.34
2     3  Dinner  Sun     No    Male  3.50       21.01
3     2  Dinner  Sun     No    Male  3.31       23.68
4     4  Dinner  Sun     No  Female  3.61       24.59

In [48]:
df

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 08_ select the data types

In [50]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [51]:
df.select_dtypes(include='number').head(5)

   total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4

In [54]:
df.select_dtypes(include=['object', 'category','number']).head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [55]:
df.select_dtypes(exclude='number').head()

      sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

# 09_ convert string to numbers

In [56]:
df = pd.DataFrame({"data": [1,2,3,4], "columns": ["a", "b", "c", "d"]}) 
df

   data columns
0     1       a
1     2       b
2     3       c
3     4       d

In [57]:
df.dtypes

data       int64
columns      str
dtype: object

In [59]:
# convert the sting data type to category data type
df.astype({'columns': 'object'}).dtypes

data        int64
columns    object
dtype: object

In [60]:
#  convert the int data type to float data type
df.astype({'data': 'float'}).dtypes

data       float64
columns        str
dtype: object

In [ ]:
# convert into numeric data type
df.to_numeric(df['object'], errors='coerce')

# 10_ Reduce Data Frame size

In [74]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [75]:
df.shape

(891, 15)

In [78]:
df.sample(frac=0.1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
256,1,1,female,NaN,0,0,79.20,C,First,woman,False,NaN,Cherbourg,yes,True
711,0,1,male,NaN,0,0,26.55,S,First,man,True,C,Southampton,no,True
337,1,1,female,41.0,0,0,134.50,C,First,woman,False,E,Cherbourg,yes,True
144,0,2,male,18.0,0,0,11.50,S,Second,man,True,NaN,Southampton,no,True
720,1,2,female,6.0,0,1,33.00,S,Second,child,False,NaN,Southampton,yes,False

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

# 11 _ copy data from clip board

In [82]:
# import data
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [84]:
df.to_excel('titanic.xlsx', index=False)

In [85]:
df = pd.read_clipboard()
df

   3    male    22  1  0
0  1  female  38.0  1  0
1  3  female  26.0  0  0
2  1  female  35.0  1  0
3  3    male  35.0  0  0
4  3    male   NaN  0  0
5  1    male  54.0  0  0
6  3    male   2.0  3  1
7  3  female  27.0  0  2
8  2  female  14.0  1  0

# 12- split dataframe into two dataset

In [86]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [87]:
df.shape

(891, 15)

In [91]:
data1 = df.sample(frac=0.50 , random_state=1)
data1.shape

(446, 15)

In [92]:
data2 = df.drop(data1.index)
data2.shape

(445, 15)

In [93]:
data1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
223,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
84,1,2,female,17.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
680,0,3,female,NaN,0,0,8.1375,Q,Third,woman,False,NaN,Queenstown,no,True
535,1,2,female,7.0,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False

In [94]:
data2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [95]:
len(data1) + len(data2)

891

# 13 -  join two dataset

In [ ]:
data = data1.append(data2, ignore_index=True)
data.shape

# 14- Filtering The Dataset

In [101]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [102]:
df.sex.unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [103]:
df[(df.sex == 'male')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [104]:
df.age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

# 15- Filtering by large categories

In [105]:
df.age.value_counts()

age
24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [106]:
df.age.value_counts().nlargest(5)

age
24.0    30
22.0    27
18.0    26
28.0    25
19.0    25
Name: count, dtype: int64

In [107]:
df.who.value_counts().index

Index(['man', 'woman', 'child'], dtype='str', name='who')

# 16- splitting a string into multiple columns

In [109]:
df = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
                   'location': ['lahore pakistan', 'karachi pakistan', 'islamabad pakistan', 'peshawar pakistan', 'quetta pakistan']})
df

      name            location
0    Alice     lahore pakistan
1      Bob    karachi pakistan
2  Charlie  islamabad pakistan
3    David   peshawar pakistan
4      Eve     quetta pakistan

In [112]:
df.location.str.split(',').str[0]

0       lahore pakistan
1      karachi pakistan
2    islamabad pakistan
3     peshawar pakistan
4       quetta pakistan
Name: location, dtype: object

# 17- Aggregate  by muliple groups/ functions

In [117]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [118]:
df.groupby('who').size()

who
child     83
man      537
woman    271
dtype: int64

In [120]:
df.groupby('sex').count()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
sex,,,,,,,,,,,,,,
female,314,314,261,314,314,314,312,314,314,314,97,312,314,314
male,577,577,453,577,577,577,577,577,577,577,106,577,577,577

In [121]:
len(df.sex)

891

In [122]:
len(df.groupby('sex'))

2

In [125]:
df.groupby(['sex','who', 'alive']).count()

                    survived  pclass  age  sibsp  parch  fare  embarked  \
sex    who   alive
female child no           15      15   15     15     15    15        15
             yes          28      28   28     28     28    28        28
       woman no           66      66   49     66     66    66        66
             yes         205     205  169    205    205   205       203
male   child no           19      19   19     19     19    19        19
             yes          21      21   21     21     21    21        21
       man   no          449     449  341    449    449   449       449
             yes          88      88   72     88     88    88        88

                    class  adult_male  deck  embark_town  alone
sex    who   alive
female child no        15          15     2           15     15
             yes       28          28     4           28     28
       woman no        66          66     4           66     66
             yes      205         205    87          203    205
male   child no        19          19     0           19     19
             yes       21          21     7           21     21
       man   no       449         449    61          449    449
             yes       88          88    38           88     88

# 18- specific rows and columns

In [127]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [128]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [129]:
df.describe().loc[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [131]:
df.describe().loc['mean': 'max']

      survived    pclass        age     sibsp     parch        fare
mean  0.383838  2.308642  29.699118  0.523008  0.381594   32.204208
std   0.486592  0.836071  14.526497  1.102743  0.806057   49.693429
min   0.000000  1.000000   0.420000  0.000000  0.000000    0.000000
25%   0.000000  2.000000  20.125000  0.000000  0.000000    7.910400
50%   0.000000  3.000000  28.000000  0.000000  0.000000   14.454200
75%   1.000000  3.000000  38.000000  1.000000  0.000000   31.000000
max   1.000000  3.000000  80.000000  8.000000  6.000000  512.329200

In [134]:
df.describe().loc['mean':'max', 'age':'fare']

            age     sibsp     parch        fare
mean  29.699118  0.523008  0.381594   32.204208
std   14.526497  1.102743  0.806057   49.693429
min    0.420000  0.000000  0.000000    0.000000
25%   20.125000  0.000000  0.000000    7.910400
50%   28.000000  0.000000  0.000000   14.454200
75%   38.000000  1.000000  0.000000   31.000000
max   80.000000  8.000000  6.000000  512.329200

In [135]:
df.groupby('sex').survived.mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

# 20- Continous to categorical data conversion

In [136]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [137]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [142]:
# creating bins
pd.cut(df.age, bins=[0, 12, 35, 60, 100], labels=['child', 'young adult', 'adult', 'senior']).head()

0    young adult
1          adult
2    young adult
3    young adult
4    young adult
Name: age, dtype: category
Categories (4, str): ['child' < 'young adult' < 'adult' < 'senior']

# 21- converting one set values into anohter

In [143]:
df.sex.head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: str

In [144]:
df.sex.map({'male':0, 'female':1}).head()

0    0
1    1
2    1
3    1
4    0
Name: sex, dtype: int64

In [145]:
df.embarked.unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [147]:
df.embarked.factorize()[0]

array([ 0,  1,  0,  0,  0,  2,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  2,
        0,  0,  1,  0,  0,  2,  0,  0,  0,  1,  0,  2,  0,  1,  1,  2,  0,
        1,  0,  1,  0,  0,  1,  0,  0,  1,  1,  2,  0,  2,  2,  1,  0,  0,
        0,  1,  0,  1,  0,  0,  1,  0,  0,  1, -1,  0,  0,  1,  1,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  2,  0,  1,  0,  0,  1,  0,  2,  0,  1,
        0,  0,  0,  1,  0,  0,  1,  2,  0,  1,  0,  1,  0,  0,  0,  0,  1,
        0,  0,  0,  1,  1,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  2,  0,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  2,
        0,  2,  0,  0,  0,  0,  0,  1,  1,  2,  0,  2,  0,  0,  0,  0,  1,
        0,  0,  0,  1,  2,  1,  0,  0,  0,  0,  2,  1,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  2,  0,  0,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  1,  0,  1,  0,  2,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  2,  0,  0,  0,  2,  0,  2,  0,  0,  0,  0,  1,  0,  0,  0,
        2,  0,  1,  1,  0,  0,  1,  1,  0,  0,  1,  2,  2,  0,  2,  0,  0,
        1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  2,
        0,  0,  1,  0,  0,  0,  1,  2,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,
        0,  2,  2,  0,  1,  1,  0,  2,  0,  1,  1,  2,  1,  1,  0,  0,  1,
        0,  1,  0,  1,  1,  0,  1,  1,  0,  0,  0,  0,  0,  0,  2,  1,  0,
        0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  2,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,
        0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  1,  0,  1,  0,  0,  0,
        2,  0,  0,  0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,
        1,  0,  1,  1,  0,  0,  0,  0,  2,  2,  0,  0,  1,  0,  0,  0,  0,
        2,  0,  0,  1,  0,  0,  0,  2,  0,  0,  0,  0,  1,  1,  1,  2,  0,
        0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,
        1,  0,  0,  1,  0,  0,  1,  0,  2,  1,  0,  0,  1,  1,  0,  0,  2,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  2,  0,  0,  0,  0,
        1,  0,  0,  1,  0,  1,  1,  0,  0,  1,  0,  0,  0,  1,  0,  2,  0,
        0,  0,  0,  1,  1,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,
        2,  2,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  2,  0,  0,
        2,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  1,
        0,  1,  0,  0,  0,  0,  0,  2,  2,  0,  0,  2,  0,  1,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        2,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,
        2,  1,  0,  1,  0,  1,  2,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,
        0,  0,  1,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
        0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  1,  2,  2,  0,  0,  0,  0,  1,  0,  0,  2,  0,  2,  0,  1,  0,
        0,  0,  0,  0,  0,  2,  0,  1,  2,  0,  0,  1,  0,  0,  0,  0,  1,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  1,  2, -1,  1,  0,  1,
        0,  0,  1,  0,  0,  0,  1,  0,  0,  1,  1,  0,  0,  0,  1,  0,  1,
        0,  0,  1,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  1,
        0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  2,  0,  0,  0,  1,  2])

# 22- Transpose a wide dataframe

In [151]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(200, 25), columns=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')[:25])

df.head()

,A,B,C,D,E,F,G,H,I,J,...,P,Q,R,S,T,U,V,W,X,Y
0,0.378020,0.462007,0.924826,0.818851,0.311780,0.431811,0.907443,0.200740,0.238482,0.825528,...,0.341475,0.792092,0.437605,0.629954,0.862227,0.027890,0.591254,0.328899,0.921324,0.305725
1,0.240766,0.047846,0.499279,0.040693,0.776007,0.519805,0.910021,0.391817,0.916109,0.800681,...,0.599578,0.651053,0.933536,0.081027,0.878983,0.121147,0.937736,0.129990,0.335709,0.256963
2,0.097986,0.071249,0.412025,0.134826,0.788914,0.798591,0.643997,0.169070,0.015983,0.414874,...,0.055975,0.234614,0.472908,0.742187,0.353660,0.287820,0.993686,0.908481,0.835511,0.365156
3,0.269944,0.076932,0.006797,0.636018,0.617290,0.053129,0.325364,0.783627,0.564582,0.083776,...,0.305261,0.297494,0.445140,0.196489,0.114286,0.578876,0.174455,0.851561,0.346582,0.710103
4,0.658023,0.480141,0.946753,0.893601,0.064497,0.753254,0.264363,0.686374,0.739201,0.634291,...,0.640427,0.784774,0.042265,0.211912,0.915905,0.411325,0.454544,0.501880,0.614150,0.977017

In [152]:
df.describe()

,A,B,C,D,E,F,G,H,I,J,...,P,Q,R,S,T,U,V,W,X,Y
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,0.506991,0.483759,0.501063,0.499364,0.500980,0.512365,0.477545,0.480235,0.532922,0.509025,...,0.498992,0.513479,0.483628,0.480394,0.494057,0.484984,0.493684,0.484733,0.510689,0.500207
std,0.294658,0.292739,0.286036,0.285031,0.295319,0.289031,0.293280,0.288266,0.307396,0.275509,...,0.304919,0.276437,0.288713,0.303989,0.275972,0.294017,0.279635,0.275296,0.296681,0.296016
min,0.005722,0.001429,0.001573,0.001378,0.002329,0.004942,0.000099,0.009329,0.005562,0.001271,...,0.009841,0.008183,0.004787,0.002389,0.005837,0.000319,0.003635,0.000793,0.004894,0.004328
25%,0.243025,0.199840,0.269116,0.252904,0.228576,0.277625,0.235057,0.226303,0.265197,0.282572,...,0.221260,0.280499,0.231764,0.197931,0.253195,0.229750,0.252932,0.269122,0.257811,0.261519
50%,0.503972,0.469433,0.489682,0.504532,0.518518,0.494657,0.445064,0.426395,0.537814,0.507881,...,0.507555,0.519893,0.472204,0.481360,0.481291,0.490495,0.491727,0.467881,0.516504,0.467215
75%,0.789273,0.727948,0.749935,0.753571,0.760326,0.787558,0.757247,0.743601,0.811269,0.733733,...,0.800708,0.745193,0.725612,0.742218,0.713348,0.737006,0.733482,0.712318,0.774914,0.771818
max,0.997592,0.998883,0.988091,0.989957,0.995891,0.991857,0.999328,0.997987,0.991018,0.999511,...,0.996561,0.991418,0.999761,0.998828,0.990304,0.999167,0.998714,0.998168,0.991296,0.999117

In [153]:
df.describe().T

   count      mean       std       min       25%       50%       75%       max
A  200.0  0.506991  0.294658  0.005722  0.243025  0.503972  0.789273  0.997592
B  200.0  0.483759  0.292739  0.001429  0.199840  0.469433  0.727948  0.998883
C  200.0  0.501063  0.286036  0.001573  0.269116  0.489682  0.749935  0.988091
D  200.0  0.499364  0.285031  0.001378  0.252904  0.504532  0.753571  0.989957
E  200.0  0.500980  0.295319  0.002329  0.228576  0.518518  0.760326  0.995891
F  200.0  0.512365  0.289031  0.004942  0.277625  0.494657  0.787558  0.991857
G  200.0  0.477545  0.293280  0.000099  0.235057  0.445064  0.757247  0.999328
H  200.0  0.480235  0.288266  0.009329  0.226303  0.426395  0.743601  0.997987
I  200.0  0.532922  0.307396  0.005562  0.265197  0.537814  0.811269  0.991018
J  200.0  0.509025  0.275509  0.001271  0.282572  0.507881  0.733733  0.999511
K  200.0  0.472235  0.298699  0.000674  0.228917  0.415948  0.724624  0.998861
L  200.0  0.520598  0.297476  0.003703  0.244969  0.538603  0.773942  0.998338
M  200.0  0.491475  0.285534  0.004021  0.256483  0.490606  0.712812  0.990006
N  200.0  0.545294  0.294073  0.000221  0.298259  0.567324  0.803097  0.995933
O  200.0  0.495662  0.295752  0.001549  0.229069  0.506469  0.763529  0.991801
P  200.0  0.498992  0.304919  0.009841  0.221260  0.507555  0.800708  0.996561
Q  200.0  0.513479  0.276437  0.008183  0.280499  0.519893  0.745193  0.991418
R  200.0  0.483628  0.288713  0.004787  0.231764  0.472204  0.725612  0.999761
S  200.0  0.480394  0.303989  0.002389  0.197931  0.481360  0.742218  0.998828
T  200.0  0.494057  0.275972  0.005837  0.253195  0.481291  0.713348  0.990304
U  200.0  0.484984  0.294017  0.000319  0.229750  0.490495  0.737006  0.999167
V  200.0  0.493684  0.279635  0.003635  0.252932  0.491727  0.733482  0.998714
W  200.0  0.484733  0.275296  0.000793  0.269122  0.467881  0.712318  0.998168
X  200.0  0.510689  0.296681  0.004894  0.257811  0.516504  0.774914  0.991296
Y  200.0  0.500207  0.296016  0.004328  0.261519  0.467215  0.771818  0.999117