# Google paly store EDA
### Complete eda analysis

# 1. IMPORT LIBRARIES

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# hide warnings
import warnings
warnings.filterwarnings('ignore')

## 2. Load the data and exploration

- Upload the csv file

In [3]:
df = pd.read_csv('E:\Machine Learning\pandas\googleplaystore.csv')

In [4]:
df.head(4)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up

In [5]:
# set option to show maximum columns and rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [7]:
df.shape

(10841, 13)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10841 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.1 MB

In [9]:
df.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

# how to make size a numeric column

In [10]:
df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
15M                    184
17M                    160
19M                    154
26M                    149
16M                    149
25M                    143
20M                    139
21M                    138
24M                    136
10M                    136
18M                    133
23M                    117
22M                    114
29M                    103
27M                     97
28M                     95
30M                     84
33M                     79
3.3M                    77
37M                     76
35M                     72
31M                     70
2.9M                    69
2.5M                    68
2.3M                    68
2.8M                    65
3.4M                    65
32M                     63
3.7M                    63
34M                     63
3.9M                    62
40M                     62
3.0M                    62
3.8M                    62
4.0M                    61
44M                     61
36M                     60
4.2M                    59
48M                     59
46M                     59
5.0M                    58
3.6M                    57
3.1M                    56
39M                     56
38M                     55
3.2M                    55
4.3M                    54
2.7M                    53
4.1M                    52
5.4M                    51
3.5M                    51
2.0M                    51
2.6M                    50
4.9M                    50
1.8M                    50
5.7M                    48
2.4M                    48
1.5M                    48
41M                     48
43M                     47
4.6M                    46
2.2M                    45
49M                     45
6.3M                    45
5.3M                    44
50M                     44
5.1M                    43
53M                     43
4.4M                    42
1.2M                    41
42M                     41
63M                     41
4.5M                    40
2.1M                    40
45M                     40
6.9M                    40
1.7M                    40
8.7M                    39
6.1M                    39
1.6M                    39
99M                     39
59M                     38
57M                     37
5.9M                    37
7.3M                    37
1.4M                    37
47M                     37
8.5M                    36
4.7M                    36
60M                     36
5.2M                    35
52M                     35
5.8M                    35
1.3M                    35
6.0M                    34
6.5M                    34
4.8M                    34
5.5M                    33
7.0M                    33
9.2M                    33
7.9M                    33
51M                     33
6.6M                    33
1.1M                    32
1.9M                    32
67M                     32
62M                     32
5.6M                    31
56M                     31
9.8M                    30
7.2M                    30
55M                     30
8.3M                    30
8.4M                    30
6.2M                    30
54M                     29
6.4M                    29
9.1M                    29
7.8M                    29
7.6M                    29
8.9M                    28
7.4M                    28
8.2M                    28
9.9M                    28
9.5M                    28
6.8M                    28
7.5M                    28
9.0M                    27
8.8M                    27
70M                     27
8.1M                    27
76M                     27
7.1M                    26
61M                     26
7.7M                    26
58M                     26
96M                     26
8.6M                    25
6.7M                    25
9.4M                    24
9.7M                    24
8.0M                    23
78M                     23
69M                     23
91M                     22
82M                     21
97M                     20
74M                     20
72M                     19
68M                     18
95M                     18
94M                     17
85M                     17
66M                     16
93M                     16
100M                    16
98M                     16
73M                     15
9.6M                    15
9.3M                    15
64M                     15
92M                     15
83M                     15
71M                     14
88M                     14
77M                     13
80M                     13
75M                     13
87M                     13
79M                     11
81M                     11
10.0M                   10
65M                     10
84M                      9
89M                      9
86M                      8
1.0M                     7
90M                      6
201k                     3
79k                      3
118k                     3
266k                     3
375k                     3
18k                      2
334k                     2
704k                     2
318k                     2
58k                      2
196k                     2
51k                      2
26k                      2
17k                      2
172k                     2
206k                     2
473k                     2
70k                      2
842k                     2
417k                     2
335k                     2
192k                     2
592k                     2
948k                     2
323k                     2
29k                      2
72k                      2
656k                     2
228k                     2
33k                      2
957k                     2
364k                     2
141k                     2
23k                      1
695k                     1
556k                     1
526k                     1
232k                     1
624k                     1
8.5k                     1
41k                      1
292k                     1
11k                      1
862k                     1
899k                     1
378k                     1
975k                     1
980k                     1
696k                     1
544k                     1
525k                     1
920k                     1
779k                     1
853k                     1
720k                     1
713k                     1
772k                     1
241k                     1
857k                     1
953k                     1
865k                     1
251k                     1
930k                     1
540k                     1
313k                     1
746k                     1
203k                     1
314k                     1
239k                     1
371k                     1
220k                     1
730k                     1
756k                     1
91k                      1
293k                     1
74k                      1
14k                      1
317k                     1
78k                      1
924k                     1
902k                     1
818k                     1
81k                      1
939k                     1
169k                     1
45k                      1
475k                     1
965k                     1
545k                     1
61k                      1
283k                     1
655k                     1
714k                     1
93k                      1
872k                     1
121k                     1
322k                     1
976k                     1
238k                     1
549k                     1
954k                     1
444k                     1
717k                     1
210k                     1
609k                     1
308k                     1
705k                     1
306k                     1
904k                     1
175k                     1
350k                     1
383k                     1
454k                     1
421k                     1
812k                     1
442k                     1
412k                     1
459k                     1
478k                     1
782k                     1
721k                     1
430k                     1
429k                     1
200k                     1
460k                     1
728k                     1
496k                     1
816k                     1
414k                     1
506k                     1
887k                     1
613k                     1
243k                     1
569k                     1
778k                     1
683k                     1
319k                     1
186k                     1
840k                     1
647k                     1
191k                     1
373k                     1
437k                     1
598k                     1
716k                     1
585k                     1
982k                     1
222k                     1
219k                     1
55k                      1
691k                     1
511k                     1
951k                     1
963k                     1
25k                      1
554k                     1
351k                     1
27k                      1
82k                      1
208k                     1
913k                     1
514k                     1
551k                     1
103k                     1
898k                     1
743k                     1
116k                     1
153k                     1
209k                     1
353k                     1
499k                     1
173k                     1
597k                     1
809k                     1
122k                     1
411k                     1
400k                     1
801k                     1
787k                     1
237k                     1
50k                      1
643k                     1
986k                     1
97k                      1
516k                     1
837k                     1
780k                     1
961k                     1
269k                     1
20k                      1
498k                     1
600k                     1
749k                     1
642k                     1
881k                     1
601k                     1
221k                     1
108k                     1
940k                     1
176k                     1
663k                     1
34k                      1
942k                     1
259k                     1
164k                     1
458k                     1
245k                     1
629k                     1
28k                      1
288k                     1
775k                     1
785k                     1
636k                     1
916k                     1
994k                     1
309k                     1
485k                     1
914k                     1
903k                     1
608k                     1
500k                     1
54k                      1
562k                     1
847k                     1
688k                     1
811k                     1
270k                     1
48k                      1
329k                     1
523k                     1
921k                     1
874k                     1
981k                     1
784k                     1
280k                     1
24k                      1
518k                     1
754k                     1
892k                     1
154k                     1
860k                     1
387k                     1
626k                     1
161k                     1
879k                     1
39k                      1
970k                     1
170k                     1
160k                     1
144k                     1
143k                     1
190k                     1
376k                     1
193k                     1
246k                     1
73k                      1
658k                     1
992k                     1
253k                     1
420k                     1
404k                     1
470k                     1
226k                     1
240k                     1
89k                      1
234k                     1
257k                     1
861k                     1
467k                     1
157k                     1
44k                      1
676k                     1
67k                      1
552k                     1
885k                     1
1020k                    1
582k                     1
619k                     1
Name: count, dtype: int64

In [11]:
df['Size'].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

---
1. M
2. k
---

In [12]:
df['Size'].isnull().sum()

np.int64(0)

-  No missing value in size column

In [13]:
# find the values have m in them
df['Size'].loc[df['Size'].str.contains('M')].value_counts().sum()

np.int64(8830)

In [14]:
# find the values have k in them
df['Size'].loc[df['Size'].str.contains('k')].value_counts().sum()

np.int64(316)

In [15]:
# find the values have varies with device in them
df['Size'].loc[df['Size'].str.contains('Varies with device')].value_counts().sum()

np.int64(1695)

In [16]:
8830+ 316+ 1695

10841

In [17]:
len(df)

10841

In [18]:
# convert the whole size column to numeric values
# lets create the function

def convert_size(size):
    if isinstance(size, str):
        if 'k' in size:
            return float (size.replace('k' , " ")) * 1024
        elif 'M' in size:
            return float (size.replace('M' , "")) *1024 *1024
        elif 'varies with device' in size:
            return np.nan
    return size

In [19]:
# lets apply this function
df['Size'] = df['Size'].apply (convert_size)

In [20]:
df['Size']

0                19922944.0
1                14680064.0
2                 9122611.2
3                26214400.0
4                 2936012.8
5                 5872025.6
6                19922944.0
7                30408704.0
8                34603008.0
9                 3250585.6
10               29360128.0
11               12582912.0
12               20971520.0
13               22020096.0
14               38797312.0
15                2831155.2
16                5767168.0
17               17825792.0
18               40894464.0
19               32505856.0
20               14680064.0
21               12582912.0
22                4404019.2
23                7340032.0
24               24117248.0
25                6291456.0
26               26214400.0
27                6396313.6
28                4823449.6
29                4404019.2
30                9646899.2
31                5452595.2
32               11534336.0
33               11534336.0
34                4404019.2
35                9646899.2
36               25165824.0
37       Varies with device
38               11534336.0
39                9856614.4
40               15728640.0
41               10485760.0
42       Varies with device
43                1258291.2
44               12582912.0
45               25165824.0
46               27262976.0
47                8388608.0
48                8283750.4
49               26214400.0
50               58720256.0
51               59768832.0
52       Varies with device
53               36700160.0
54               34603008.0
55               34603008.0
56                5872025.6
57               56623104.0
58                 205824.0
59                3774873.6
60                5976883.2
61               17825792.0
62                9017753.6
63                2516582.4
64               28311552.0
65                2831155.2
66                2621440.0
67       Varies with device
68       Varies with device
69                7340032.0
70               36700160.0
71               16777216.0
72               16777216.0
73       Varies with device
74               17825792.0
75                3565158.4
76                9332326.4
77                4089446.4
78                3040870.4
79               39845888.0
80               33554432.0
81               38797312.0
82               15728640.0
83                5662310.4
84               18874368.0
85       Varies with device
86               39845888.0
87                1153433.6
88       Varies with device
89       Varies with device
90                8283750.4
91               36700160.0
92       Varies with device
93               17825792.0
94               19922944.0
95               14680064.0
96                2306867.2
97                4718592.0
98               17825792.0
99               14680064.0
100              10276044.8
101              22020096.0
102      Varies with device
103              54525952.0
104              14680064.0
105              26214400.0
106               9437184.0
107      Varies with device
108              12582912.0
109      Varies with device
110              36700160.0
111               7025459.2
112              31457280.0
113               5976883.2
114               3040870.4
115              17825792.0
116               3040870.4
117      Varies with device
118      Varies with device
119               2726297.6
120               4404019.2
121               7444889.6
122              59768832.0
123               3879731.2
124              23068672.0
125              25165824.0
126               7759462.4
127              22020096.0
128               3565158.4
129               3040870.4
130               3250585.6
131               6710886.4
132               3355443.2
133               8598323.2
134              10380902.4
135               3040870.4
136              24117248.0
137               4823449.6
138               3250585.6
139      Varies with device
140               5138022.4
141               9961472.0
142      Varies with device
143      Varies with device
144      Varies with device
145      Varies with device
146      Varies with device
147               4404019.2
148               5662310.4
149      Varies with device
150               2936012.8
151               5242880.0
152      Varies with device
153               6186598.4
154              13631488.0
155               7444889.6
156               7025459.2
157      Varies with device
158              17825792.0
159              19922944.0
160               7025459.2
161              22020096.0
162      Varies with device
163               2831155.2
164              38797312.0
165              15728640.0
166              24117248.0
167              19922944.0
168              24117248.0
169              76546048.0
170               5138022.4
171               7130316.8
172      Varies with device
173      Varies with device
174               3040870.4
175               3670016.0
176               4194304.0
177              22020096.0
178               2411724.8
179      Varies with device
180               7549747.2
181              10485760.0
182               6396313.6
183               2202009.6
184              44040192.0
185               7654604.8
186              31457280.0
187      Varies with device
188      Varies with device
189      Varies with device
190              30408704.0
191      Varies with device
192      Varies with device
193      Varies with device
194              36700160.0
195               9542041.6
196              26214400.0
197               4089446.4
198              18874368.0
199              12582912.0
200              22020096.0
201      Varies with device
202      Varies with device
203      Varies with device
204      Varies with device
205              57671680.0
206               3355443.2
207      Varies with device
208      Varies with device
209                 23552.0
210              16777216.0
211      Varies with device
212              14680064.0
213              38797312.0
214      Varies with device
215      Varies with device
216              11534336.0
217              26214400.0
218               7654604.8
219               6815744.0
220              26214400.0
221               3250585.6
222      Varies with device
223               1572864.0
224               7864320.0
225               9017753.6
226      Varies with device
227               1258291.2
228      Varies with device
229      Varies with device
230      Varies with device
231              40894464.0
232              14680064.0
233              19922944.0
234               7130316.8
235              40894464.0
236      Varies with device
237              14680064.0
238              20971520.0
239      Varies with device
240      Varies with device
241              27262976.0
242              53477376.0
243              42991616.0
244              20971520.0
245      Varies with device
246              12582912.0
247              50331648.0
248              10485760.0
249              23068672.0
250              11534336.0
251               8912896.0
252               9017753.6
253      Varies with device
254              29360128.0
255              29360128.0
256              38797312.0
257               9437184.0
258              48234496.0
259      Varies with device
260              14680064.0
261      Varies with device
262              27262976.0
263              24117248.0
264      Varies with device
265      Varies with device
266              14680064.0
267              20971520.0
268      Varies with device
269      Varies with device
270              27262976.0
271              53477376.0
272              42991616.0
273              20971520.0
274      Varies with device
275              12582912.0
276              50331648.0
277              10485760.0
278              23068672.0
279              11534336.0
280               8912896.0
281               9017753.6
282      Varies with device
283              29360128.0
284      Varies with device
285      Varies with device
286      Varies with device
287              40894464.0
288              14680064.0
289              19922944.0
290               7130316.8
291              40894464.0
292      Varies with device
293              36700160.0
294      Varies with device
295              30408704.0
296              42991616.0
297      Varies with device
298               5138022.4
299              28311552.0
300              33554432.0
301              12582912.0
302              15728640.0
303              11534336.0
304              29360128.0
305               2306867.2
306               3565158.4
307               8703180.8
308               4508876.8
309               4928307.2
310              10485760.0
311              15728640.0
312               7444889.6
313              22020096.0
314               6396313.6
315      Varies with device
316              15728640.0
317              11534336.0
318              30408704.0
319               3460300.8
320      Varies with device
321              23068672.0
322              41943040.0
323              10485760.0
324               9542041.6
325               4928307.2
326              39845888.0
327      Varies with device
328               7025459.2
329              38797312.0
330      Varies with device
331               8178892.8
332              19922944.0
333               5976883.2
334              36700160.0
335      Varies with device
336      Varies with device
337              17825792.0
338      Varies with device
339      Varies with device
340      Varies with device
341      Varies with device
342      Varies with device
343               9227468.8
344      Varies with device
345              16777216.0
346              11534336.0
347              11534336.0
348      Varies with device
349              15728640.0
350               6920601.6
351      Varies with device
352               6920601.6
353      Varies with device
354      Varies with device
355               5347737.6
356      Varies with device
357              18874368.0
358               4194304.0
359      Varies with device
360      Varies with device
361      Varies with device
362              38797312.0
363      Varies with device
364              23068672.0
365      Varies with device
366               3460300.8
367              33554432.0
368              38797312.0
369      Varies with device
370      Varies with device
371      Varies with device
372      Varies with device
373      Varies with device
374              17825792.0
375      Varies with device
376      Varies with device
377              36700160.0
378              41943040.0
379              63963136.0
380              69206016.0
381      Varies with device
382      Varies with device
383              11534336.0
384                 80896.0
385      Varies with device
386      Varies with device
387              26214400.0
388              14680064.0
389      Varies with device
390      Varies with device
391      Varies with device
392      Varies with device
393      Varies with device
394      Varies with device
395              25165824.0
396      Varies with device
397              17825792.0
398               8703180.8
399      Varies with device
400               8598323.2
401      Varies with device
402      Varies with device
403      Varies with device
404      Varies with device
405               8808038.4
406      Varies with device
407      Varies with device
408               4194304.0
409              33554432.0
410      Varies with device
411      Varies with device
412      Varies with device
413               6396313.6
414      Varies with device
415      Varies with device
416               2936012.8
417      Varies with device
418      Varies with device
419               3460300.8
420              41943040.0
421               2306867.2
422      Varies with device
423               4508876.8
424               4928307.2
425               2411724.8
426               2411724.8
427      Varies with device
428              11534336.0
429               2831155.2
430              14680064.0
431      Varies with device
432              13631488.0
433               3879731.2
434              10485760.0
435              13631488.0
436              10485760.0
437              13631488.0
438               9227468.8
439               5767168.0
440              20971520.0
441              30408704.0
442      Varies with device
443      Varies with device
444              11534336.0
445      Varies with device
446              17825792.0
447              17825792.0
448      Varies with device
449      Varies with device
450                120832.0
451      Varies with device
452              16777216.0
453               5347737.6
454      Varies with device
455              46137344.0
456               7654604.8
457              31457280.0
458                711680.0
459      Varies with device
460               1677721.6
461              19922944.0
462      Varies with device
463      Varies with device
464      Varies with device
465              11534336.0
466      Varies with device
467      Varies with device
468      Varies with device
469      Varies with device
470              24117248.0
471              27262976.0
472      Varies with device
473      Varies with device
474      Varies with device
475      Varies with device
476      Varies with device
477               6501171.2
478              20971520.0
479                 18432.0
480               1258291.2
481              17825792.0
482      Varies with device
483              15728640.0
484      Varies with device
485              58720256.0
486              12582912.0
487              11534336.0
488              30408704.0
489      Varies with device
490              41943040.0
491      Varies with device
492              55574528.0
493               3250585.6
494              25165824.0
495              24117248.0
496               5242880.0
497              46137344.0
498              28311552.0
499               6396313.6
500      Varies with device
501              22020096.0
502              11534336.0
503              22020096.0
504              25165824.0
505              32505856.0
506              28311552.0
507               6501171.2
508      Varies with device
509              12582912.0
510               8388608.0
511               6186598.4
512               8283750.4
513               5242880.0
514               1468006.4
515              13631488.0
516              41943040.0
517              13631488.0
518              19922944.0
519               5242880.0
520              19922944.0
521              28311552.0
522               3145728.0
523              13631488.0
524               7549747.2
525              26214400.0
526      Varies with device
527               5976883.2
528               5767168.0
529      Varies with device
530               6815744.0
531               6081740.8
532      Varies with device
533               3984588.8
534              42991616.0
535               8283750.4
536               2936012.8
537              20971520.0
538              15728640.0
539              29360128.0
540              10066329.6
541              13631488.0
542              15728640.0
543              41943040.0
544              58720256.0
545              12582912.0
546               9856614.4
547              30408704.0
548              11534336.0
549              19922944.0
550              24117248.0
551      Varies with device
552              28311552.0
553      Varies with device
554              19922944.0
555              47185920.0
556              22020096.0
557              41943040.0
558              26214400.0
559              15728640.0
560              25165824.0
561      Varies with device
562              11534336.0
563              39845888.0
564              32505856.0
565               6396313.6
566              28311552.0
567              33554432.0
568              13631488.0
569              66060288.0
570              46137344.0
571      Varies with device
572              16777216.0
573              29360128.0
574      Varies with device
575               6186598.4
576              13631488.0
577               9437184.0
578              20971520.0
579               8283750.4
580              29360128.0
581              51380224.0
582              28311552.0
583              18874368.0
584              14680064.0
585              28311552.0
586              42991616.0
587              39845888.0
588               5767168.0
589              28311552.0
590               7549747.2
591              22020096.0
592               9227468.8
593              39845888.0
594      Varies with device
595              11534336.0
596               6815744.0
597              27262976.0
598              19922944.0
599               6396313.6
600              80740352.0
601               9961472.0
602              14680064.0
603              39845888.0
604              16777216.0
605               3565158.4
606               4928307.2
607               5242880.0
608               5138022.4
609               5138022.4
610              16777216.0
611               4089446.4
612               4613734.4
613               5033164.8
614               4718592.0
615              73400320.0
616               5138022.4
617               3879731.2
618               5138022.4
619              16777216.0
620               4823449.6
621               3774873.6
622              22020096.0
623              13631488.0
624               9122611.2
625               9646899.2
626               7235174.4
627              40894464.0
628               8388608.0
629               4089446.4
630              14680064.0
631              11534336.0
632              13631488.0
633               9751756.8
634               5242880.0
635              10485760.0
636               5242880.0
637               5242880.0
638               3774873.6
639              19922944.0
640               5242880.0
641              10276044.8
642              14680064.0
643               5242880.0
644               5138022.4
645               5767168.0
646              11534336.0
647               3984588.8
648               5242880.0
649               8598323.2
650              22020096.0
651              12582912.0
652              10485760.0
653               3460300.8
654              26214400.0
655              15728640.0
656              10485760.0
657               5138022.4
658               4613734.4
659               3670016.0
660               8178892.8
661               9437184.0
662              15728640.0
663              19922944.0
664              58720256.0
665              39845888.0
666              16777216.0
667               5242880.0
668              28311552.0
669               4928307.2
670      Varies with device
671               3565158.4
672               5138022.4
673              26214400.0
674              30408704.0
675               8493465.6
676              14680064.0
677              28311552.0
678               4089446.4
679              13631488.0
680               5242880.0
681               5767168.0
682              16777216.0
683               5033164.8
684              14680064.0
685               4928307.2
686               3879731.2
687               5138022.4
688               3670016.0
689               4718592.0
690      Varies with device
691              37748736.0
692               4718592.0
693              19922944.0
694              14680064.0
695              80740352.0
696              22020096.0
697               8283750.4
698               9751756.8
699      Varies with device
700              18874368.0
701              18874368.0
702              22020096.0
703               3460300.8
704              25165824.0
705              40894464.0
706               3355443.2
707               5347737.6
708              11534336.0
709              28311552.0
710              38797312.0
711      Varies with device
712              27262976.0
713              11534336.0

In [21]:
# install columns
df['Installs'].unique()

<StringArray>
[       '10,000+',       '500,000+',     '5,000,000+',    '50,000,000+',
       '100,000+',        '50,000+',     '1,000,000+',    '10,000,000+',
         '5,000+',   '100,000,000+', '1,000,000,000+',         '1,000+',
   '500,000,000+',            '50+',           '100+',           '500+',
            '10+',             '1+',             '5+',             '0+',
              '0']
Length: 21, dtype: str

In [22]:
df['Size'].value_counts()

Size
Varies with device    1695
11534336.0             198
12582912.0             196
14680064.0             194
13631488.0             191
15728640.0             184
17825792.0             160
19922944.0             154
27262976.0             149
16777216.0             149
10485760.0             146
26214400.0             143
20971520.0             139
22020096.0             138
25165824.0             136
18874368.0             133
24117248.0             117
23068672.0             114
30408704.0             103
28311552.0              97
29360128.0              95
31457280.0              84
34603008.0              79
3460300.8               77
38797312.0              76
36700160.0              72
32505856.0              70
3040870.4               69
2621440.0               68
2411724.8               68
2936012.8               65
3565158.4               65
33554432.0              63
3879731.2               63
35651584.0              63
4089446.4               62
41943040.0              62
3145728.0               62
3984588.8               62
4194304.0               61
46137344.0              61
37748736.0              60
4404019.2               59
50331648.0              59
48234496.0              59
5242880.0               58
3774873.6               57
3250585.6               56
40894464.0              56
39845888.0              55
3355443.2               55
4508876.8               54
2831155.2               53
4299161.6               52
5662310.4               51
3670016.0               51
2097152.0               51
2726297.6               50
5138022.4               50
1887436.8               50
5976883.2               48
2516582.4               48
1572864.0               48
42991616.0              48
45088768.0              47
4823449.6               46
2306867.2               45
51380224.0              45
6606028.8               45
5557452.8               44
52428800.0              44
5347737.6               43
55574528.0              43
4613734.4               42
1258291.2               41
44040192.0              41
66060288.0              41
4718592.0               40
2202009.6               40
47185920.0              40
7235174.4               40
1782579.2               40
9122611.2               39
6396313.6               39
1677721.6               39
103809024.0             39
61865984.0              38
59768832.0              37
6186598.4               37
7654604.8               37
1468006.4               37
49283072.0              37
8912896.0               36
4928307.2               36
62914560.0              36
5452595.2               35
54525952.0              35
6081740.8               35
1363148.8               35
6291456.0               34
6815744.0               34
5033164.8               34
5767168.0               33
7340032.0               33
9646899.2               33
8283750.4               33
53477376.0              33
6920601.6               33
1153433.6               32
1992294.4               32
70254592.0              32
65011712.0              32
5872025.6               31
58720256.0              31
10276044.8              30
7549747.2               30
57671680.0              30
8703180.8               30
8808038.4               30
6501171.2               30
56623104.0              29
6710886.4               29
9542041.6               29
8178892.8               29
7969177.6               29
9332326.4               28
7759462.4               28
8598323.2               28
10380902.4              28
9961472.0               28
7130316.8               28
7864320.0               28
9437184.0               27
9227468.8               27
73400320.0              27
8493465.6               27
79691776.0              27
7444889.6               26
63963136.0              26
8074035.2               26
60817408.0              26
100663296.0             26
9017753.6               25
7025459.2               25
9856614.4               24
10171187.2              24
8388608.0               23
81788928.0              23
72351744.0              23
95420416.0              22
85983232.0              21
101711872.0             20
77594624.0              20
75497472.0              19
71303168.0              18
99614720.0              18
98566144.0              17
89128960.0              17
69206016.0              16
97517568.0              16
104857600.0             16
102760448.0             16
76546048.0              15
10066329.6              15
9751756.8               15
67108864.0              15
96468992.0              15
87031808.0              15
74448896.0              14
92274688.0              14
80740352.0              13
83886080.0              13
78643200.0              13
91226112.0              13
82837504.0              11
84934656.0              11
68157440.0              10
88080384.0               9
93323264.0               9
90177536.0               8
1048576.0                7
94371840.0               6
205824.0                 3
80896.0                  3
120832.0                 3
272384.0                 3
384000.0                 3
18432.0                  2
342016.0                 2
720896.0                 2
325632.0                 2
59392.0                  2
200704.0                 2
52224.0                  2
26624.0                  2
17408.0                  2
176128.0                 2
210944.0                 2
484352.0                 2
71680.0                  2
862208.0                 2
427008.0                 2
343040.0                 2
196608.0                 2
606208.0                 2
970752.0                 2
330752.0                 2
29696.0                  2
73728.0                  2
671744.0                 2
233472.0                 2
33792.0                  2
979968.0                 2
372736.0                 2
144384.0                 2
23552.0                  1
711680.0                 1
569344.0                 1
538624.0                 1
237568.0                 1
638976.0                 1
8704.0                   1
41984.0                  1
299008.0                 1
11264.0                  1
882688.0                 1
920576.0                 1
387072.0                 1
998400.0                 1
1003520.0                1
712704.0                 1
557056.0                 1
537600.0                 1
942080.0                 1
797696.0                 1
873472.0                 1
737280.0                 1
730112.0                 1
790528.0                 1
246784.0                 1
877568.0                 1
975872.0                 1
885760.0                 1
257024.0                 1
952320.0                 1
552960.0                 1
320512.0                 1
763904.0                 1
207872.0                 1
321536.0                 1
244736.0                 1
379904.0                 1
225280.0                 1
747520.0                 1
774144.0                 1
93184.0                  1
300032.0                 1
75776.0                  1
14336.0                  1
324608.0                 1
79872.0                  1
946176.0                 1
923648.0                 1
837632.0                 1
82944.0                  1
961536.0                 1
173056.0                 1
46080.0                  1
486400.0                 1
988160.0                 1
558080.0                 1
62464.0                  1
289792.0                 1
670720.0                 1
731136.0                 1
95232.0                  1
892928.0                 1
123904.0                 1
329728.0                 1
999424.0                 1
243712.0                 1
562176.0                 1
976896.0                 1
454656.0                 1
734208.0                 1
215040.0                 1
623616.0                 1
315392.0                 1
721920.0                 1
313344.0                 1
925696.0                 1
179200.0                 1
358400.0                 1
392192.0                 1
464896.0                 1
431104.0                 1
831488.0                 1
452608.0                 1
421888.0                 1
470016.0                 1
489472.0                 1
800768.0                 1
738304.0                 1
440320.0                 1
439296.0                 1
204800.0                 1
471040.0                 1
745472.0                 1
507904.0                 1
835584.0                 1
423936.0                 1
518144.0                 1
908288.0                 1
627712.0                 1
248832.0                 1
582656.0                 1
796672.0                 1
699392.0                 1
326656.0                 1
190464.0                 1
860160.0                 1
662528.0                 1
195584.0                 1
381952.0                 1
447488.0                 1
612352.0                 1
733184.0                 1
599040.0                 1
1005568.0                1
227328.0                 1
224256.0                 1
56320.0                  1
707584.0                 1
523264.0                 1
973824.0                 1
986112.0                 1
25600.0                  1
567296.0                 1
359424.0                 1
27648.0                  1
83968.0                  1
212992.0                 1
934912.0                 1
526336.0                 1
564224.0                 1
105472.0                 1
919552.0                 1
760832.0                 1
118784.0                 1
156672.0                 1
214016.0                 1
361472.0                 1
510976.0                 1
177152.0                 1
611328.0                 1
828416.0                 1
124928.0                 1
420864.0                 1
409600.0                 1
820224.0                 1
805888.0                 1
242688.0                 1
51200.0                  1
658432.0                 1
1009664.0                1
99328.0                  1
528384.0                 1
857088.0                 1
798720.0                 1
984064.0                 1
275456.0                 1
20480.0                  1
509952.0                 1
614400.0                 1
766976.0                 1
657408.0                 1
902144.0                 1
615424.0                 1
226304.0                 1
110592.0                 1
962560.0                 1
180224.0                 1
678912.0                 1
34816.0                  1
964608.0                 1
265216.0                 1
167936.0                 1
468992.0                 1
250880.0                 1
644096.0                 1
28672.0                  1
294912.0                 1
793600.0                 1
803840.0                 1
651264.0                 1
937984.0                 1
1017856.0                1
316416.0                 1
496640.0                 1
935936.0                 1
924672.0                 1
622592.0                 1
512000.0                 1
55296.0                  1
575488.0                 1
867328.0                 1
704512.0                 1
830464.0                 1
276480.0                 1
49152.0                  1
336896.0                 1
535552.0                 1
943104.0                 1
894976.0                 1
1004544.0                1
802816.0                 1
286720.0                 1
24576.0                  1
530432.0                 1
772096.0                 1
913408.0                 1
157696.0                 1
880640.0                 1
396288.0                 1
641024.0                 1
164864.0                 1
900096.0                 1
39936.0                  1
993280.0                 1
174080.0                 1
163840.0                 1
147456.0                 1
146432.0                 1
194560.0                 1
385024.0                 1
197632.0                 1
251904.0                 1
74752.0                  1
673792.0                 1
1015808.0                1
259072.0                 1
430080.0                 1
413696.0                 1
481280.0                 1
231424.0                 1
245760.0                 1
91136.0                  1
239616.0                 1
263168.0                 1
881664.0                 1
478208.0                 1
160768.0                 1
45056.0                  1
692224.0                 1
68608.0                  1
565248.0                 1
906240.0                 1
1044480.0                1
595968.0                 1
633856.0                 1
Name: count, dtype: int64

In [23]:
df['Installs'].isnull().sum()

np.int64(0)

In [24]:
# remove + sign
# convert the column into inte
# remove . 
# remove + sign and commas, convert to integer
df['Installs'] = df['Installs'].apply(
    lambda x: int(str(x).replace('+', '').replace(',', ''))
              if pd.notnull(x) else x
)

In [25]:
df['Installs'].value_counts()

Installs
1000000       1579
10000000      1252
100000        1169
10000         1054
1000           908
5000000        752
100            719
500000         539
50000          479
5000           477
100000000      409
10             386
500            330
50000000       289
50             205
5               82
500000000       72
1               67
1000000000      58
0               15
Name: count, dtype: int64

In [26]:
df.describe()

            Rating       Reviews      Installs
count  9367.000000  1.084100e+04  1.084100e+04
mean      4.191513  4.441119e+05  1.546291e+07
std       0.515735  2.927629e+06  8.502557e+07
min       1.000000  0.000000e+00  0.000000e+00
25%       4.000000  3.800000e+01  1.000000e+03
50%       4.300000  2.094000e+03  1.000000e+05
75%       4.500000  5.476800e+04  5.000000e+06
max       5.000000  7.815831e+07  1.000000e+09

In [27]:
df['Price'].value_counts()

Price
0          10041
$0.99        148
$2.99        129
$1.99         73
$4.99         72
$3.99         63
$1.49         46
$5.99         30
$2.49         26
$9.99         21
$6.99         13
$399.99       12
$14.99        11
$4.49          9
$7.99          7
$3.49          7
$24.99         7
$29.99         7
$5.49          6
$19.99         6
$11.99         5
$12.99         5
$8.99          5
$6.49          5
$10.00         3
$16.99         3
$1.00          3
$2.00          3
$7.49          2
$9.00          2
$79.99         2
$10.99         2
$33.99         2
$39.99         2
$3.95          2
$1.70          2
$17.99         2
$13.99         2
$8.49          2
$1.50          1
$15.99         1
$74.99         1
$3.88          1
$25.99         1
$400.00        1
$3.02          1
$1.76          1
$4.84          1
$4.77          1
$1.61          1
$2.50          1
$1.59          1
$1.29          1
$5.00          1
$299.99        1
$379.99        1
$37.99         1
$18.99         1
$389.99        1
$19.90         1
$1.75          1
$14.00         1
$4.85          1
$46.99         1
$109.99        1
$154.99        1
$3.08          1
$2.59          1
$4.80          1
$1.96          1
$19.40         1
$3.90          1
$4.59          1
$15.46         1
$3.04          1
$4.29          1
$2.60          1
$3.28          1
$4.60          1
$28.99         1
$2.95          1
$2.90          1
$1.97          1
$200.00        1
$89.99         1
$2.56          1
$30.99         1
$3.61          1
$394.99        1
$1.26          1
$1.20          1
$1.04          1
Name: count, dtype: int64

In [28]:
# let see how many values have $ sign
df['Price'].loc[df['Price'].str.contains(\$)].value_counts().sum()

SyntaxError: unexpected character after line continuation character (786256072.py, line 2)